language: csharp

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker build -t starcounter/starcounter.nova.samples .

script:
  - docker run -it --rm starcounter/starcounter.nova.samples
