language: csharp

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker build -t starcounter/starcounter.core.samples .

script:
  - docker run starcounter/starcounter.core.samples
