language: csharp

dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-rc4-004771

before_install:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/b/boost-defaults/libboost-system-dev_1.58.0.1ubuntu1_amd64.deb
  - sudo dpkg -i libboost-system-dev_1.58.0.1ubuntu1_amd64.deb

script:
  - dotnet restore
  - dotnet run
